export const CERTIFICATE_SUBMIT = 'CERTIFICATE_SUBMIT';

export const CERTIFICATE_VIEW = 'CERTIFICATE_VIEW';

export const CERTIFICATES_SUMMARY = 'CERTIFICATES_SUMMARY';

export const CERTIFICATES_SUMMARY_OWNER = 'CERTIFICATES_SUMMARY_OWNER';

export const POLICY_SUBMIT = 'POLICY_SUBMIT';

export const POLICY_VIEW = 'POLICY_VIEW';

export const POLICIES_SUMMARY = 'POLICIES_SUMMARY';
